"""Stage prompts for P46: Incubation Protocol (The Walk)."""

ANALYSIS_PROMPT = """\
Analyze the following strategic question from your perspective. Be thorough \
and specific — identify tensions, risks, opportunities, dependencies, and \
non-obvious dynamics. This analysis will feed a creative incubation process, \
so surface the hardest, most unresolved aspects of the problem.

QUESTION:
{question}
"""

COMPRESSION_PROMPT = """\
You are a compression engine. Below are analyses of a strategic question from \
multiple independent perspectives. Your job is to distill ALL of this into the \
single irreducible core tension — the one thing that makes this problem genuinely \
hard.

Rules:
- Output ONLY the core tension in 1-2 sentences. Nothing else.
- No preamble, no explanation, no bullet points.
- The tension should capture WHY this problem resists easy answers.
- Be brutally concise.

ORIGINAL QUESTION:
{question}

ANALYSES:
{analyses}
"""

FREE_ASSOCIATION_PROMPT = """\
You are a free-association engine. You have no persona, no expertise, no agenda.

Below is a tension. Your job is to freely associate across completely unrelated \
domains. For each association, name the domain and describe the parallel or \
metaphor in 2-3 sentences.

Rules:
- Produce exactly 7 associations from DIFFERENT domains.
- Domains to draw from: biology, physics, history, literature, music, sports, \
cooking, architecture, mythology, mathematics, ecology, theater, astronomy, \
games, textiles, geology, dance, chemistry, cartography, gardening.
- Do NOT reference business, strategy, management, or consulting.
- Do NOT try to solve anything. Just associate freely.
- Each association should surprise — avoid obvious metaphors.

THE TENSION:
{tension}
"""

EVALUATION_PROMPT = """\
You are a strategic translator. Below is a business question, its core tension, \
and a set of free associations generated by an unbiased creative process.

Your job:
1. Review each association honestly. Most will be noise — that is expected.
2. Identify 1-3 associations that genuinely reframe the original problem in a \
   way the initial analyses missed.
3. For each selected association, explain:
   - WHY this metaphor illuminates something new
   - WHAT specific strategic implication it suggests
   - HOW the team could act on this insight

Be rigorous. If no association adds real value, say so. Do not force connections.

Finally, produce a **Synthesis** section that weaves the best reframes into a \
coherent strategic narrative with concrete next steps.

ORIGINAL QUESTION:
{question}

CORE TENSION:
{tension}

FREE ASSOCIATIONS:
{associations}

ORIGINAL ANALYSES:
{analyses}
"""
