"""Stage prompts for P6: TRIZ Inversion Protocol."""

FAILURE_GENERATION_PROMPT = """\
You are participating in a TRIZ Inversion exercise. Your sole job is to \
guarantee that the following plan or initiative FAILS spectacularly.

Be specific, creative, and ruthless. Think about:
- Operational failures (execution, resources, timing)
- Financial failures (cash flow, pricing, hidden costs)
- Market failures (competition, demand, positioning)
- Technical failures (architecture, scaling, integration)
- Reputational failures (trust, PR, stakeholder backlash)
- People failures (talent, culture, leadership)

For each failure mode, provide:
1. A short title (5-10 words)
2. A detailed description of HOW it causes failure
3. Which category it falls into

Output as a numbered list. Aim for 5-10 failure modes.

THE PLAN/INITIATIVE:
{question}
"""

DEDUPLICATION_PROMPT = """\
You are a failure-mode analyst. Below are failure modes generated by multiple \
independent analysts examining the same plan. Your job:

1. Merge duplicates and near-duplicates (keep the most detailed version)
2. Assign each unique failure to exactly one category:
   - operational, financial, market, technical, reputational, people
3. Output a clean JSON array of objects with fields:
   "id" (int starting at 1), "title", "description", "category"

Failure modes from all analysts:
{all_failures}
"""

INVERSION_PROMPT = """\
You are a solutions architect. Below are categorized failure modes from a TRIZ \
Inversion exercise. For EACH failure mode, generate the specific mitigation or \
solution that would PREVENT that failure.

The solution should be:
- Actionable (something a team can implement)
- Specific (not generic advice)
- Proportional to the severity of the failure

Output as a JSON array of objects with fields:
"failure_id" (int matching the input), "solution_title", "solution_description"

Failure modes:
{failures_json}
"""

RANKING_PROMPT = """\
You are a risk analyst. Below are failure modes with their solutions from a \
TRIZ Inversion exercise. Score each failure mode on two dimensions:

- severity: How catastrophic if it occurs? (1=minor annoyance, 5=existential)
- likelihood: How probable without mitigation? (1=unlikely, 5=near-certain)

Output as a JSON array of objects with fields:
"failure_id" (int), "severity" (int 1-5), "likelihood" (int 1-5), \
"composite" (severity × likelihood), "rationale" (one sentence)

Sort by composite score descending.

Failure modes and solutions:
{failures_and_solutions}
"""

SYNTHESIS_PROMPT = """\
You are a strategic advisor synthesizing the results of a TRIZ Inversion \
exercise — a structured method where analysts first identified every way a \
plan could fail, then inverted those failures into solutions.

Using the ranked failure modes and their solutions below, produce a final \
actionable briefing with:

1. **Executive Summary** (2-3 sentences): The overall risk landscape
2. **Critical Risks** (top 3-5 by composite score): Each with the failure mode, \
   why it matters, and the specific mitigation
3. **Quick Wins**: Low-effort mitigations that address multiple failure modes
4. **Recommended Action Sequence**: Ordered steps the team should take

Be direct, specific, and strategic. No filler.

THE ORIGINAL QUESTION/PLAN:
{question}

RANKED FAILURES AND SOLUTIONS:
{ranked_results}
"""
