"""Stage prompts for P7: Wicked Questions Protocol."""

TENSION_GENERATION_PROMPT = """\
You are participating in a Wicked Questions exercise. Your job is to surface \
the deep, irresolvable paradoxes and strategic tensions hidden within the \
following topic.

A "wicked question" captures two things that are BOTH true simultaneously \
but seem to contradict each other. They take the form:
"How is it that [X is true] AND [Y is also true]?"

Think about tensions between:
- Short-term vs. long-term priorities
- Growth vs. sustainability
- Control vs. autonomy
- Innovation vs. reliability
- Speed vs. quality
- Internal culture vs. external demands
- Individual needs vs. collective needs
- What we say vs. what we do

For each tension, provide:
1. Side A: The first truth (stated as a factual assertion)
2. Side B: The contradicting truth (also stated as a factual assertion)
3. Why both are simultaneously true
4. The strategic implication of this tension

Generate 5-8 tension pairs. Be specific to THIS topic — no generic platitudes.

THE TOPIC:
{question}
"""

WICKEDNESS_TEST_PROMPT = """\
You are a strategic paradox evaluator. Below are tension pairs generated by \
multiple analysts. Your job is to apply a strict 3-part wickedness test to \
each one.

A tension pair is "truly wicked" ONLY if it passes ALL THREE tests:

**Test 1 — Both Sides True:** Both assertions are genuinely, simultaneously \
true (not hypothetical, not aspirational — actually true right now).

**Test 2 — Cannot Choose One:** You cannot resolve the tension by simply \
picking one side. Choosing either side exclusively would cause serious harm. \
The organization must somehow hold both.

**Test 3 — Creates Real Tension:** The paradox creates genuine strategic \
discomfort. It is not a false dichotomy, a problem with an obvious solution, \
or a tension that can be easily sequenced ("do X first, then Y").

For each tension pair, output:
- "id" (int)
- "side_a" (string)
- "side_b" (string)
- "test_1_pass" (boolean) and "test_1_reasoning" (string)
- "test_2_pass" (boolean) and "test_2_reasoning" (string)
- "test_3_pass" (boolean) and "test_3_reasoning" (string)
- "is_wicked" (boolean — true only if all 3 tests pass)
- "wicked_question" (string — formatted as "How is it that [X] AND [Y]?" \
  ONLY if is_wicked is true, otherwise empty string)

Output as a JSON array.

ALL TENSION PAIRS:
{all_tensions}
"""

RANKING_PROMPT = """\
You are a strategic advisor. Below are wicked questions that have passed a \
strict wickedness test — these are genuine, irresolvable paradoxes.

Rank them by strategic relevance using these criteria:
- **Urgency**: How soon does this tension demand attention? (1-5)
- **Impact**: How much does this tension affect the organization's trajectory? (1-5)
- **Hiddenness**: How likely is leadership to be blind to this tension? (1-5)

Output as a JSON array of objects with fields:
"id" (int), "wicked_question" (string), "urgency" (int 1-5), \
"impact" (int 1-5), "hiddenness" (int 1-5), \
"composite" (urgency + impact + hiddenness), \
"strategic_implication" (string — 2-3 sentences on why this matters and \
what it means for decision-making)

Sort by composite score descending.

WICKED QUESTIONS:
{wicked_questions}
"""

SYNTHESIS_PROMPT = """\
You are a strategic advisor synthesizing the results of a Wicked Questions \
exercise — a structured method for surfacing the deep paradoxes that an \
organization must learn to hold rather than resolve.

Using the ranked wicked questions below, produce a strategic briefing with:

1. **Paradox Landscape** (2-3 sentences): What pattern do these tensions \
   reveal about the organization's current position?
2. **Top Wicked Questions** (the top-ranked ones): For each, state the \
   question, explain why it's genuinely irresolvable, and describe what it \
   means for strategy
3. **Polarity Management Recommendations**: For the top tensions, suggest \
   how to hold BOTH sides (not resolve, but manage the polarity)
4. **Conversation Starters**: 2-3 questions leadership should discuss based \
   on these paradoxes

Be direct and strategic. These are meant to provoke productive discomfort, \
not provide easy answers.

THE ORIGINAL TOPIC:
{question}

RANKED WICKED QUESTIONS:
{ranked_results}
"""
