"""Prompts for the P26 Crazy Eights protocol."""

RAPID_GENERATION_PROMPT = """\
You are participating in a Crazy Eights rapid ideation exercise.

Question / challenge:
{question}

Your role: {agent_name}
{system_prompt}

Generate EXACTLY 8 ideas in response to the question above. Rules:
- Each idea must be 1-2 sentences MAX. Be terse and punchy.
- No self-editing. No filtering. Quantity over quality.
- Push for variety — wild ideas are welcome alongside practical ones.
- Do NOT explain or qualify your ideas. Just state them.

Respond in JSON:
{{
  "ideas": [
    "idea 1",
    "idea 2",
    "idea 3",
    "idea 4",
    "idea 5",
    "idea 6",
    "idea 7",
    "idea 8"
  ]
}}
"""

CLUSTER_PROMPT = """\
You are organizing ideas from a Crazy Eights rapid ideation session.

Question / challenge:
{question}

Here are all {total_ideas} ideas generated by the team:
{ideas_block}

Group these ideas into thematic clusters. Each cluster should have:
- A short theme label (3-5 words)
- The list of ideas that belong to it

An idea should appear in exactly one cluster. Aim for 3-7 clusters.

Respond in JSON:
{{
  "clusters": [
    {{
      "theme": "short theme label",
      "ideas": ["idea text 1", "idea text 2"]
    }}
  ]
}}
"""

DOT_VOTE_PROMPT = """\
You are voting in a Crazy Eights dot-voting round.

Question / challenge:
{question}

Your role: {agent_name}
{system_prompt}

Here are the clustered ideas from the team:
{clusters_block}

You have EXACTLY 3 votes. Rules:
- Vote for the 3 ideas you believe have the most potential.
- You CANNOT vote for your own ideas. Your ideas were: {own_ideas_block}
- Spread your votes across different clusters if possible.
- For each vote, give a 1-sentence reason.

Respond in JSON:
{{
  "votes": [
    {{"idea": "exact idea text you are voting for", "reason": "why"}},
    {{"idea": "exact idea text you are voting for", "reason": "why"}},
    {{"idea": "exact idea text you are voting for", "reason": "why"}}
  ]
}}
"""

DEVELOP_CONCEPTS_PROMPT = """\
You are developing the winning ideas from a Crazy Eights rapid ideation session.

Question / challenge:
{question}

The team generated {total_ideas} ideas, voted, and selected these top concepts:
{top_ideas_block}

For each top idea, develop it into a fuller concept:
1. **Concept name**: A memorable 3-5 word title
2. **Core idea**: Expand the original idea into 2-3 sentences
3. **Rationale**: Why this could work (2-3 sentences)
4. **Key risk**: The biggest obstacle or assumption to validate
5. **Next step**: One concrete action to move this forward

Respond in JSON:
{{
  "developed_concepts": [
    {{
      "original_idea": "the original idea text",
      "concept_name": "short title",
      "core_idea": "expanded description",
      "rationale": "why it could work",
      "key_risk": "biggest obstacle",
      "next_step": "concrete action"
    }}
  ]
}}
"""
